"""PR title and body builders. Ported from the gh heredoc (owl.sh:1456-1469)."""

from __future__ import annotations

_OWL_URL = "https://github.com/murcoutinho/owl"


def pr_title(prefix: str, plan_slug: str) -> str:
    return f"{prefix}{plan_slug}"


def pr_body(*, plan_slug: str, plan_content: str, rounds_completed: int, rounds_total: int) -> str:
    return (
        f"## {plan_slug}\n\n"
        f"**Review rounds completed:** {rounds_completed} / {rounds_total}\n\n"
        f"## Plan\n\n{plan_content}\n\n"
        f"---\nGenerated by [Owl]({_OWL_URL})\n"
    )
