#!/bin/bash
#
# Owl — autonomous dev agent
#
# Flow per plan:
# 1. Find next plan
# 2. Reset all repos to main & pull
# 3. Execute plan via Claude Code (told to commit but NOT push)
# 4. Create branch in repos that are ahead of main, move commits there
# 5. Mark pending review
# 6. Review loop: reviewer LLMs check, Claude Code fixes (commits, no push)
# 7. Push branch, open PRs
# 8. Switch all repos back to main
# 9. Write done file
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLAN_DIR="$SCRIPT_DIR/../plan"
LOG_FILE="$SCRIPT_DIR/../agent.log"
WORK_DIR="$SCRIPT_DIR/../.work"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOCK_FILE="$SCRIPT_DIR/../.agent.lock"
REVIEW_ITERATIONS=2
RETRY_WAIT=600
MAX_RETRIES=50

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

acquire_lock() {
  if ! mkdir "$LOCK_FILE" 2>/dev/null; then
    echo "Another agent instance is running (lock: $LOCK_FILE). Exiting."
    exit 1
  fi
  trap 'rm -rf "$LOCK_FILE"' EXIT INT TERM
}

is_rate_limited() {
  local output="$1"
  echo "$output" | grep -qiE "rate.?limit|too many requests|429|overloaded|capacity|quota exceeded|try again"
}

retry_on_limit() {
  local desc="$1"
  shift
  local attempt=0
  while true; do
    attempt=$((attempt + 1))
    local rc=0
    RETRY_OUTPUT=$("$@" 2>&1) || rc=$?
    if [ $rc -eq 0 ] && ! is_rate_limited "$RETRY_OUTPUT"; then
      return 0
    fi
    if is_rate_limited "$RETRY_OUTPUT"; then
      if [ $attempt -ge $MAX_RETRIES ]; then
        log "RATE LIMIT: $desc — gave up after $attempt attempts."
        return 1
      fi
      log "RATE LIMIT: $desc — attempt $attempt hit rate limit. Retrying in $((RETRY_WAIT / 60)) minutes..."
      sleep $RETRY_WAIT
    else
      return $rc
    fi
  done
}

# ─── Step 2: Reset all repos to main & pull ───
reset_all_repos_to_main() {
  log "Resetting all repos to main and pulling..."
  while IFS= read -r -d '' repo_dir; do
    local repo_root="$(dirname "$repo_dir")"
    local repo_name="$(basename "$repo_root")"

    # Skip repos with no commits
    if ! git -C "$repo_root" rev-parse --verify HEAD >/dev/null 2>&1; then
      continue
    fi

    local current_branch
    current_branch=$(git -C "$repo_root" branch --show-current 2>/dev/null)

    if [ "$current_branch" != "main" ]; then
      log "  $repo_name: switching from '$current_branch' to main"
      git -C "$repo_root" checkout main 2>/dev/null
    fi

    # Pull latest (non-destructive, fast-forward only)
    git -C "$repo_root" pull --ff-only origin main 2>/dev/null || true

  done < <(find "$PROJECT_DIR" -maxdepth 2 -name ".git" -type d -print0 2>/dev/null)
}


# ─── Step 7: Push branches and open PRs ───
push_and_open_prs() {
  local branch_name="$1"
  local plan_name="$2"
  local plan_file="$3"
  local plan_work_dir="$4"
  local review_rounds_completed="$5"
  local review_rounds_total="$6"

  local plan_content
  plan_content=$(cat "$plan_file")

  while IFS= read -r -d '' repo_dir; do
    local repo_root="$(dirname "$repo_dir")"
    local repo_name="$(basename "$repo_root")"

    # Skip repos that don't have this branch
    if ! git -C "$repo_root" rev-parse --verify "$branch_name" >/dev/null 2>&1; then
      continue
    fi

    # Skip if no commits on branch beyond main
    if [ -z "$(git -C "$repo_root" log main.."$branch_name" --oneline 2>/dev/null)" ]; then
      git -C "$repo_root" branch -d "$branch_name" 2>/dev/null || true
      continue
    fi

    log "Pushing branch '$branch_name' in $repo_name..."
    git -C "$repo_root" checkout "$branch_name" 2>/dev/null
    git -C "$repo_root" push -u origin "$branch_name" 2>/dev/null

    log "Opening PR in $repo_name..."
    local pr_url
    pr_url=$(cd "$repo_root" && gh pr create \
      --title "[owl] ${plan_name%.md}" \
      --body "$(cat <<EOF
## ${plan_name%.md}

**Review rounds completed:** ${review_rounds_completed} / ${review_rounds_total}

## Plan

\`\`\`
${plan_content}
\`\`\`

---
Generated by [Owl](https://github.com/murcoutinho/owl)
EOF
)" 2>&1) || true

    if [ -n "$pr_url" ]; then
      log "PR created in $repo_name: $pr_url"
      echo "$repo_name	$pr_url" >> "$plan_work_dir/pull_requests.tsv"
    else
      log "Failed to create PR in $repo_name."
    fi

  done < <(find "$PROJECT_DIR" -maxdepth 2 -name ".git" -type d -print0 2>/dev/null)
}

# ─── Step 8: Switch all repos back to main ───
switch_all_to_main() {
  while IFS= read -r -d '' repo_dir; do
    local repo_root="$(dirname "$repo_dir")"
    if git -C "$repo_root" rev-parse --verify HEAD >/dev/null 2>&1; then
      git -C "$repo_root" checkout main 2>/dev/null || true
    fi
  done < <(find "$PROJECT_DIR" -maxdepth 2 -name ".git" -type d -print0 2>/dev/null)
}

# ─── Execute plan ───
execute_plan() {
  local plan_file="$1"
  local plan_name="$(basename "$plan_file")"

  log "========================================="
  log "Found plan: $plan_name"
  log "========================================="

  local plan_content
  plan_content="$(cat "$plan_file")"

  local work_id="$(date '+%Y%m%d_%H%M%S')_${plan_name%.md}"
  local plan_work_dir="$WORK_DIR/$work_id"
  mkdir -p "$plan_work_dir"

  local branch_name="owl/${plan_name%.md}"

  # ── Step 2: Reset to main & pull ──
  reset_all_repos_to_main

  # ── Step 3: Execute plan via Claude Code ──
  log "[Step 3] Executing plan via Claude Code..."
  cd "$PROJECT_DIR"

  local plan_prompt_file="$plan_work_dir/plan_prompt.txt"
  cat > "$plan_prompt_file" <<PLANEOF
$plan_content

IMPORTANT INSTRUCTIONS:
- Do NOT commit, push, or create branches. Just write the code changes.
- The agent handles all git operations.
PLANEOF

  retry_on_limit "Plan execution" bash -c 'claude --print --dangerously-skip-permissions --model claude-sonnet-4-6 - < "$1"' _ "$plan_prompt_file"
  local exit_code=$?
  local exec_output="$RETRY_OUTPUT"
  echo "$exec_output" >> "$LOG_FILE"
  echo "$exec_output" > "$plan_work_dir/execution.log"

  if [ $exit_code -ne 0 ] || [ -z "$exec_output" ] || echo "$exec_output" | grep -qi "^Execution error$"; then
    log "Plan execution failed (exit=$exit_code, output_len=${#exec_output}). Will retry next cycle."
    # Discard any partial changes
    while IFS= read -r -d '' repo_dir; do
      local repo_root="$(dirname "$repo_dir")"
      git -C "$repo_root" checkout -- . 2>/dev/null
      git -C "$repo_root" clean -fd 2>/dev/null
    done < <(find "$PROJECT_DIR" -maxdepth 2 -name ".git" -type d -print0 2>/dev/null)
    return 1
  fi

  log "Plan execution completed."

  # ── Step 4: Find dirty repos, create branch, commit ──
  log "[Step 4] Creating branch and committing changes..."
  : > "$plan_work_dir/review_input_1.tsv"
  while IFS= read -r -d '' repo_dir; do
    local repo_root="$(dirname "$repo_dir")"
    local repo_name="$(basename "$repo_root")"

    # Skip repos with no changes
    if git -C "$repo_root" diff --quiet 2>/dev/null && \
       git -C "$repo_root" diff --cached --quiet 2>/dev/null && \
       [ -z "$(git -C "$repo_root" ls-files --others --exclude-standard 2>/dev/null)" ]; then
      continue
    fi

    local main_hash="NONE"
    if git -C "$repo_root" rev-parse --verify HEAD >/dev/null 2>&1; then
      main_hash=$(git -C "$repo_root" rev-parse HEAD)
    fi

    log "  $repo_name: changes detected → creating branch '$branch_name'"

    # Create and switch to branch
    git -C "$repo_root" checkout -b "$branch_name" 2>/dev/null

    # Stage and commit
    git -C "$repo_root" add -A 2>/dev/null
    git -C "$repo_root" commit -m "[owl] ${plan_name%.md} — execution" 2>/dev/null

    local after_hash
    after_hash=$(git -C "$repo_root" rev-parse HEAD)
    local short_hash
    short_hash=$(git -C "$repo_root" rev-parse --short HEAD)

    log "  $repo_name: committed ($short_hash)"

    printf '%s\t%s\t%s\t%s\n' "$repo_name" "$repo_root" "$main_hash" "$after_hash" >> "$plan_work_dir/review_input_1.tsv"
    printf '%s\t%s\n' "$repo_name" "$short_hash" >> "$plan_work_dir/commits.tsv"

  done < <(find "$PROJECT_DIR" -maxdepth 2 -name ".git" -type d -print0 2>/dev/null)

  # ── Step 5: Mark pending ──
  echo "$plan_file" > "$plan_work_dir/pending"
  echo "$branch_name" > "$plan_work_dir/branch"

  # ── Step 6: Review loop ──
  run_review_loop "$plan_file" "$plan_name" "$plan_work_dir"
}

# ─── Review loop ───
run_review_loop() {
  local plan_file="$1"
  local plan_name="$2"
  local plan_work_dir="$3"

  local branch_name=""
  [ -f "$plan_work_dir/branch" ] && branch_name=$(cat "$plan_work_dir/branch")

  # Ensure we're on the right branch
  if [ -n "$branch_name" ]; then
    while IFS= read -r -d '' repo_dir; do
      local repo_root="$(dirname "$repo_dir")"
      if git -C "$repo_root" rev-parse --verify "$branch_name" >/dev/null 2>&1; then
        git -C "$repo_root" checkout "$branch_name" 2>/dev/null
      fi
    done < <(find "$PROJECT_DIR" -maxdepth 2 -name ".git" -type d -print0 2>/dev/null)
  fi

  local reviews_done=0
  if [ -f "$plan_work_dir/state" ]; then
    reviews_done=$(sed -n 's/^reviews_done=\([0-9]*\)$/\1/p' "$plan_work_dir/state" 2>/dev/null)
    reviews_done=${reviews_done:-0}
  fi

  local review_rounds_completed=$reviews_done
  local reviews_skipped=0

  for i in $(seq $((reviews_done + 1)) $REVIEW_ITERATIONS); do
    log "-----------------------------------------"
    log "[Iteration $i/$REVIEW_ITERATIONS] Review phase"
    log "-----------------------------------------"

    local manifest="$plan_work_dir/review_input_$i.tsv"

    if [ ! -s "$manifest" ]; then
      log "No manifest for round $i. Skipping."
      reviews_skipped=$((reviews_skipped + 1))
      continue
    fi

    # Build review prompt — tell the LLM where to look, it reads the diff itself
    local review_prompt_file="$plan_work_dir/review_prompt_$i.txt"
    {
      echo "You are a code reviewer. Review the changes in the commits listed below for bugs, security issues, code quality problems, and correctness. Be concise — return only actionable fixes, no praise. If nothing needs fixing, respond with exactly: LGTM"
      echo ""
      echo "Use git diff to inspect the changes. Here are the repos and commit ranges to review:"
      echo ""
      while IFS=$'\t' read -r repo_name repo_root base head; do
        if [ "$base" != "NONE" ] && [ -n "$base" ]; then
          echo "- Repo: $repo_name (path: $repo_root) — run: git -C $repo_root diff $base $head"
        else
          echo "- Repo: $repo_name (path: $repo_root) — run: git -C $repo_root show $head"
        fi
      done < "$manifest"
    } > "$review_prompt_file"

    # Launch reviewers in parallel
    log "Spawning Codex reviewer..."
    local codex_review_file="$plan_work_dir/codex_review_$i.txt"
    (
      rc=0
      retry_on_limit "Codex review" bash -c 'codex exec --full-auto --skip-git-repo-check - < "$1"' _ "$review_prompt_file" || rc=$?
      echo "$RETRY_OUTPUT"
      exit $rc
    ) > "$codex_review_file" 2>&1 &
    local codex_pid=$!

    log "Spawning Claude Code reviewer..."
    local claude_review_file="$plan_work_dir/claude_review_$i.txt"
    (
      rc=0
      retry_on_limit "Claude review" bash -c 'claude --print --dangerously-skip-permissions --model claude-sonnet-4-6 - < "$1"' _ "$review_prompt_file" || rc=$?
      echo "$RETRY_OUTPUT"
      exit $rc
    ) > "$claude_review_file" 2>&1 &
    local claude_pid=$!

    local codex_ok=true claude_ok=true
    wait $codex_pid || codex_ok=false
    log "Codex review complete (success=$codex_ok)."
    wait $claude_pid || claude_ok=false
    log "Claude Code review complete (success=$claude_ok)."

    if ! $codex_ok && ! $claude_ok; then
      log "Both reviewers failed. Skipping fix phase for iteration $i."
      reviews_skipped=$((reviews_skipped + 1))
      continue
    fi

    local codex_review=""
    local claude_review=""
    [ -f "$codex_review_file" ] && codex_review=$(cat "$codex_review_file")
    [ -f "$claude_review_file" ] && claude_review=$(cat "$claude_review_file")

    local combined_review="## Codex Review

$codex_review

## Claude Code Review

$claude_review"

    echo "$combined_review" > "$plan_work_dir/combined_review_$i.txt"
    review_rounds_completed=$i

    local codex_trimmed claude_trimmed
    codex_trimmed=$(echo "$codex_review" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    claude_trimmed=$(echo "$claude_review" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

    if [ "$codex_trimmed" = "LGTM" ] && [ "$claude_trimmed" = "LGTM" ]; then
      log "Both reviewers say LGTM. No fixes needed."
      break
    fi

    # ── Fix phase: Claude writes fixes, we commit ──
    log "[Iteration $i/$REVIEW_ITERATIONS] Fix phase"

    local fix_prompt_file="$plan_work_dir/fix_prompt_$i.txt"
    cat > "$fix_prompt_file" <<FIXEOF
You received the following code review feedback on recent changes in this project. Apply the necessary fixes. Only change what the review asks for — do not refactor unrelated code.

IMPORTANT: Do NOT commit, push, or create branches. Just write the code fixes.

## Review Feedback

$combined_review
FIXEOF

    log "Applying fixes via Claude Code..."
    retry_on_limit "Apply fixes" bash -c 'claude --print --dangerously-skip-permissions --model claude-sonnet-4-6 - < "$1"' _ "$fix_prompt_file"
    echo "$RETRY_OUTPUT" | tee -a "$LOG_FILE" > "$plan_work_dir/fixes_$i.log"

    # Commit fixes in repos on the branch that have changes
    local next_manifest="$plan_work_dir/review_input_$((i + 1)).tsv"
    : > "$next_manifest"
    while IFS= read -r -d '' repo_dir; do
      local repo_root="$(dirname "$repo_dir")"
      local repo_name="$(basename "$repo_root")"
      local current_branch
      current_branch=$(git -C "$repo_root" branch --show-current 2>/dev/null)

      # Only commit in repos on the plan's branch with changes
      if [ "$current_branch" != "$branch_name" ]; then
        continue
      fi
      if git -C "$repo_root" diff --quiet 2>/dev/null && \
         git -C "$repo_root" diff --cached --quiet 2>/dev/null && \
         [ -z "$(git -C "$repo_root" ls-files --others --exclude-standard 2>/dev/null)" ]; then
        continue
      fi

      local before_hash
      before_hash=$(git -C "$repo_root" rev-parse HEAD)

      git -C "$repo_root" add -A 2>/dev/null
      git -C "$repo_root" commit -m "[owl] ${plan_name%.md} — review fix iteration $i" 2>/dev/null

      local after_hash
      after_hash=$(git -C "$repo_root" rev-parse HEAD)
      local short_hash
      short_hash=$(git -C "$repo_root" rev-parse --short HEAD)

      log "  $repo_name: fix committed ($short_hash)"
      printf '%s\t%s\t%s\t%s\n' "$repo_name" "$repo_root" "$before_hash" "$after_hash" >> "$next_manifest"
      printf '%s\t%s\n' "$repo_name" "$short_hash" >> "$plan_work_dir/commits.tsv"
    done < <(find "$PROJECT_DIR" -maxdepth 2 -name ".git" -type d -print0 2>/dev/null)

    review_rounds_completed=$i
    echo "reviews_done=$i" > "$plan_work_dir/state"
  done

  # ── Step 7: Push and open PRs ──
  local reviews_successful=$(( review_rounds_completed > reviews_skipped ? review_rounds_completed - reviews_skipped : 0 ))
  if [ -n "$branch_name" ]; then
    log "[Step 7] Pushing branches and opening PRs..."
    push_and_open_prs "$branch_name" "$plan_name" "$plan_file" "$plan_work_dir" "$reviews_successful" "$REVIEW_ITERATIONS"
  fi

  # ── Step 8: Switch back to main ──
  log "[Step 8] Switching all repos back to main..."
  switch_all_to_main

  # ── Step 9: Write done file ──
  log "========================================="
  log "Plan '$plan_name' completed."
  log "========================================="

  mkdir -p "$PLAN_DIR/done"
  local done_name="${plan_name%.md}_$(date '+%Y%m%d_%H%M%S').done.md"
  local done_path="$PLAN_DIR/done/$done_name"

  {
    cat "$plan_file"
    echo ""
    echo "---"
    echo ""
    echo "## Execution Summary"
    echo ""
    echo "- **Completed:** $(date '+%Y-%m-%d %H:%M:%S')"
    echo "- **Review rounds:** $reviews_successful completed / $REVIEW_ITERATIONS total"
    echo "- **Repos changed:**"
    if [ -f "$plan_work_dir/commits.tsv" ]; then
      while IFS=$'\t' read -r repo_name hash; do
        echo "  - \`$repo_name\` — commit \`$hash\`"
      done < "$plan_work_dir/commits.tsv"
    else
      echo "  - (none)"
    fi
    echo "- **Pull requests:**"
    if [ -f "$plan_work_dir/pull_requests.tsv" ]; then
      while IFS=$'\t' read -r repo_name pr_url; do
        echo "  - \`$repo_name\` — $pr_url"
      done < "$plan_work_dir/pull_requests.tsv"
    else
      echo "  - (none)"
    fi
    echo ""
    for r in $(seq 1 $review_rounds_completed); do
      echo "### Review Round $r"
      echo ""
      if [ -f "$plan_work_dir/combined_review_$r.txt" ]; then
        cat "$plan_work_dir/combined_review_$r.txt"
      else
        echo "(skipped)"
      fi
      echo ""
    done
  } > "$done_path"

  rm "$plan_file"
  rm -f "$plan_work_dir/pending"
  rm -f "$plan_work_dir/state"
  log "Wrote done file: $done_name"
}

# ─── Resume pending reviews ───
resume_pending_reviews() {
  local resumed=false
  for pending_file in "$WORK_DIR"/*/pending; do
    [ -f "$pending_file" ] || continue
    local plan_work_dir="$(dirname "$pending_file")"
    local plan_file
    plan_file="$(cat "$pending_file")"
    local plan_name="$(basename "$plan_file")"

    if [ ! -f "$plan_file" ]; then
      log "Pending review for '$plan_name' but plan file is gone. Cleaning up."
      rm -f "$pending_file"
      continue
    fi

    log "Resuming pending review for: $plan_name"
    run_review_loop "$plan_file" "$plan_name" "$plan_work_dir"
    resumed=true
  done
  if $resumed; then return 0; else return 1; fi
}

# ─── Main check loop ───
check_plans() {
  log "Checking for plans in $PLAN_DIR..."

  if resume_pending_reviews; then
    log "Resumed pending reviews. Will check for new plans next cycle."
    return
  fi

  local found=0
  while IFS= read -r -d '' plan_file; do
    [ -f "$plan_file" ] || continue
    found=1
    if ! execute_plan "$plan_file"; then
      log "Plan failed — will retry next cycle. Stopping current cycle."
      return
    fi
  done < <(find "$PLAN_DIR" -maxdepth 1 -name "*.md" -print0 2>/dev/null | sort -z)

  if [ $found -eq 0 ]; then
    log "No plans found."
  fi
}

# ─── Main ───
acquire_lock

log "Dev Agent started. Checking every 10 minutes."
log "Plan directory: $PLAN_DIR"
log "Project directory: $PROJECT_DIR"
log "Review iterations: $REVIEW_ITERATIONS"

while true; do
  check_plans
  log "Sleeping 10 minutes..."
  sleep 600
done
